create onDragEnd handler for board
shuto410/board-game-simulator pull request #15
Opened 2022-10-22 03:23 UTC by sho25

BoardのonDradEnd handler
現状あるPlaceをBoard内で自由に動かせます

2022-10-23 10:07 UTC, sho25 commented on index.html
> +    style="margin: 0; position: fixed; top: 0; bottom: 0; left: 0; right: 0"
ドラッグしたときの画面のスクロール防止

2022-11-01 01:51 UTC, shuto410 requested changes

2022-11-01 01:51 UTC, shuto410 commented on src/App.tsx
> +      ...(board?.childElements ? board.childElements : []),
```suggestion
      ...(board?.childElements ?? []),
```
多分こうできる？

2022-11-01 01:51 UTC, shuto410 commented on src/hooks/boardEditUtils.tsx
> +    ?.map((gameElement: GameElement) => {
[nitpick]
ここ推論効いてそうだからこのGameElementの型宣言はいらない？

2022-11-01 01:51 UTC, shuto410 commented on src/hooks/boardEditUtils.tsx
> +    ?.map((gameElement: GameElement) => {
上に同じく

2022-11-01 01:51 UTC, shuto410 commented on src/hooks/boardEditUtils.tsx
> +const findGameElementChildById = (
[nitpick]
exportしてるほうの関数上に書いとく方がすこ

2022-11-01 01:51 UTC, shuto410 commented on src/type.ts
> +  parent?: string;
parentIdにしようぜ

2022-11-01 09:03 UTC, sho25 commented on src/type.ts
> +  parent?: string;
ずっとそれ思いながら書いてた
（忘れてた）

2022-11-01 09:17 UTC, sho25 commented on src/hooks/boardEditUtils.tsx
> +const findGameElementChildById = (
Cの名残

2022-11-01 10:08 UTC, shuto410 approved these changes

2022-11-01 10:41 UTC, merged