Create type definition
shuto410/board-game-simulator pull request #9
Opened 2022-09-25 04:02 UTC by sho25

idea branch

2022-09-25 04:12 UTC, sho25 commented
id忘れてた

2022-09-25 11:34 UTC, shuto410 requested changes

2022-09-25 11:34 UTC, shuto410 commented on src/type.ts
> +type Elements = {
これをBasePropertiesにして下のGameElementsをGameElementってのがlooks good to meです

2022-09-25 11:34 UTC, shuto410 commented on src/type.ts
> +type GameElements = Card | DummyCard | Deck | Place | Board;
```suggestion
type GameElement = Card | DummyCard | Deck | Place | Board;
```

2022-09-25 11:34 UTC, shuto410 commented on src/type.ts
> +type Elements = {
```suggestion
type BaseProperties = {
```

2022-09-25 11:34 UTC, shuto410 commented on src/type.ts
> +type Card = Elements & {
```suggestion
type Card = BaseProperties & {
```

2022-09-25 11:34 UTC, shuto410 commented on src/type.ts
> +type Deck = Elements & {
```suggestion
type Deck = BaseProperties & {
```

2022-09-25 11:34 UTC, shuto410 commented on src/type.ts
> +type Place = Elements & {
```suggestion
type Place = BaseProperties & {
```

2022-09-25 11:34 UTC, shuto410 commented on src/type.ts
> +type Board = Elements & {};
```suggestion
type Board = BaseProperties & {};
```

2022-10-09 06:51 UTC, shuto410 approved these changes
LGTM!

2022-10-09 07:11 UTC, merged